/**
 * Build the illustrated-board catalog from whatever is in `assets/boards/`.
 *
 * Every `<theme>-<n>.webp` in that folder becomes a selectable board: the
 * theme is the slug before the trailing number, the number is the variant. A
 * file with no trailing number is variant 1 of a theme named after the whole
 * stem. Nothing is registered by hand — dropping a file in and rebuilding is
 * the entire process of adding a board, which is the only way a catalog of a
 * hundred-plus files stays honest.
 *
 * Output is `src/generated/board-catalog.json`, committed so that a fresh clone
 * type-checks without running anything. It is regenerated by every `npm run
 * build` / `watch` / `typecheck` (see package.json), so it cannot drift from
 * the folder for longer than one build.
 *
 * Geometry — the artwork's aspect ratio and where its pinnable panel sits —
 * comes from three places, most specific wins:
 *
 *   1. `assets/boards/board-overrides.json` → `boards["<key>"].inset`
 *   2. `assets/boards/board-overrides.json` → `themes["<theme>"].inset`
 *   3. `assets/boards/board-overrides.json` → `defaultInset`
 *
 * The default fits the generator's usual composition (a rectangular panel with
 * posts either side and an ornament on top); an override is for a board whose
 * panel sits somewhere else, like the original weathered board with its roof.
 * Dimensions are read from the WebP header directly — no image library, so
 * this runs anywhere Node does.
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";

const BOARDS = "assets/boards";
const OVERRIDES = join(BOARDS, "board-overrides.json");
const OUTPUT = "src/generated/board-catalog.json";

/** `<theme>-<variant>.webp`, or just `<theme>.webp`. */
const FILENAME = /^(?<theme>[a-z0-9]+(?:-[a-z0-9]+)*?)(?:-(?<variant>\d+))?\.webp$/;

/**
 * Width and height of a WebP file, from its container header.
 *
 * Three layouts exist. `VP8X` (extended — anything with alpha, which is every
 * board here) carries a 24-bit canvas size at byte 24; lossless `VP8L` packs
 * two 14-bit values starting at byte 21; plain lossy `VP8 ` has 14-bit values
 * at byte 26. All little-endian, all stored as size-minus-one for the first
 * two.
 */
function webpDimensions(bytes) {
  if (bytes.toString("latin1", 0, 4) !== "RIFF" || bytes.toString("latin1", 8, 12) !== "WEBP") {
    throw new Error("not a WebP file");
  }
  const chunk = bytes.toString("latin1", 12, 16);
  if (chunk === "VP8X") {
    return {
      width: 1 + bytes.readUIntLE(24, 3),
      height: 1 + bytes.readUIntLE(27, 3),
    };
  }
  if (chunk === "VP8L") {
    const b = bytes;
    return {
      width: 1 + (b[21] | ((b[22] & 0x3f) << 8)),
      height: 1 + ((b[22] >> 6) | (b[23] << 2) | ((b[24] & 0x0f) << 10)),
    };
  }
  if (chunk === "VP8 ") {
    return {
      width: bytes.readUInt16LE(26) & 0x3fff,
      height: bytes.readUInt16LE(28) & 0x3fff,
    };
  }
  throw new Error(`unknown WebP chunk "${chunk}"`);
}

async function readOverrides() {
  try {
    return JSON.parse(await readFile(OVERRIDES, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") return {};
    throw error;
  }
}

const overrides = await readOverrides();
const defaultInset = overrides.defaultInset ?? { top: 15, right: 10.5, bottom: 18, left: 10.5 };

const files = (await readdir(BOARDS)).filter((file) => file.endsWith(".webp")).sort();
const boards = [];
const warnings = [];

for (const file of files) {
  const match = FILENAME.exec(file);
  if (!match) {
    warnings.push(`${file}: name is not <theme>-<n>.webp, skipped`);
    continue;
  }
  const theme = match.groups.theme;
  const variant = match.groups.variant ? Number(match.groups.variant) : 1;
  const key = `${theme}-${variant}`;

  const bytes = await readFile(join(BOARDS, file));
  const { width, height } = webpDimensions(bytes.subarray(0, 32));

  const inset = {
    ...defaultInset,
    ...(overrides.themes?.[theme]?.inset ?? {}),
    ...(overrides.boards?.[key]?.inset ?? {}),
  };

  boards.push({ key, theme, variant, file, width, height, inset });
}

// Theme first, then variant numerically — the order the editor lists them in.
boards.sort((a, b) => a.theme.localeCompare(b.theme) || a.variant - b.variant);

for (const key of Object.keys(overrides.boards ?? {})) {
  if (!boards.some((board) => board.key === key)) warnings.push(`override for "${key}" matches no file`);
}
for (const theme of Object.keys(overrides.themes ?? {})) {
  if (!boards.some((board) => board.theme === theme)) warnings.push(`override for theme "${theme}" matches no file`);
}

await mkdir(dirname(OUTPUT), { recursive: true });
await writeFile(OUTPUT, `${JSON.stringify({ boards }, null, 2)}\n`);

const themes = new Set(boards.map((board) => board.theme)).size;
console.log(`board catalog: ${boards.length} board(s) across ${themes} theme(s) -> ${OUTPUT}`);
for (const warning of warnings) console.warn(`  warning: ${warning}`);
